// Code generated by hack/gen-rbac from config/mappings. DO NOT EDIT.
//
// Regenerate with: make generate-rbac
//
// These markers are what controller-gen turns into the manager ClusterRole.
// They are derived from the FieldMapping documents, so onboarding a vendor
// needs no Go edit: drop in a mapping and regenerate. The previous hand-written
// markers were the one place a vendor port was not pure data, and a forgotten
// group surfaced only at runtime as an apiserver Forbidden error.

package translation

// +kubebuilder:rbac:groups=config.openshift.io,resources=dataprocessingunits/finalizers;servicefunctionchains/finalizers,verbs=update
// +kubebuilder:rbac:groups=config.openshift.io,resources=dataprocessingunits/status;servicefunctionchains/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=config.openshift.io,resources=dataprocessingunits;servicefunctionchains,verbs=get;list;watch;update;patch
// +kubebuilder:rbac:groups=dpu.amd.com,resources=dscdevices;dscfirmwares;dscnodepolicies;dscprofiles,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=provisioning.dpu.nvidia.com,resources=bfbs;dpudevices;dpuflavors;dpus,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=svc.dpu.nvidia.com,resources=dpuservices,verbs=get;list;watch;create;update;patch;delete
