/*
Copyright 2026 Kartikey Gupta.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command gen-rbac derives the translation controller's +kubebuilder:rbac
// markers from the FieldMapping documents.
//
// This closes the last place a vendor port was not pure data. controller-gen
// builds the ClusterRole from marker comments, so until now adding a vendor
// meant hand-editing a comment in pkg/translation and hoping nobody forgot --
// a failure that surfaces only at runtime, as a Forbidden error from the
// apiserver after everything else looks correct.
//
// Every group, resource and verb below is implied by the mapping itself: the
// source kind is read, status-updated and finalized; the emitted target kinds
// are fully managed. Nothing here is a judgement call, which is exactly why it
// belongs in a generator rather than in a reviewer's head.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/kartikeyg0104/opi-nvidia-dpf-adapter/pkg/mapping"
)

const (
	// Verbs on an OPI source: watched and reconciled, never created by us.
	sourceVerbs = "get;list;watch;update;patch"
	// Verbs on an emitted target: fully owned, including delete for GC.
	targetVerbs = "get;list;watch;create;update;patch;delete"
)

func main() {
	var mappingDir, out, pkg string
	flag.StringVar(&mappingDir, "mapping-dir", "config/mappings", "directory of FieldMapping documents")
	flag.StringVar(&out, "out", "pkg/translation/zz_generated_rbac.go", "file to write")
	flag.StringVar(&pkg, "package", "translation", "package name for the generated file")
	check := flag.Bool("check", false, "verify the file on disk is up to date; do not write")
	flag.Parse()

	specs, err := mapping.LoadDir(mappingDir)
	if err != nil {
		fatalf("loading mappings from %s: %v", mappingDir, err)
	}

	want, err := render(specs, pkg, mappingDir)
	if err != nil {
		fatalf("rendering: %v", err)
	}

	if *check {
		got, err := os.ReadFile(out)
		if err != nil {
			fatalf("reading %s: %v (run: make generate-rbac)", out, err)
		}
		if !bytes.Equal(got, want) {
			fatalf("%s is stale: a mapping was changed without regenerating RBAC.\n"+
				"Run: make generate-rbac", out)
		}
		fmt.Printf("%s is up to date\n", out)
		return
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		fatalf("%v", err)
	}
	if err := os.WriteFile(out, want, 0o644); err != nil {
		fatalf("writing %s: %v", out, err)
	}
	fmt.Printf("wrote %s\n", out)
}

// rule is one marker line: a group plus the resources needed on it.
type rule struct {
	group     string
	resources []string
	verbs     string
}

func render(specs []*mapping.Spec, pkg, mappingDir string) ([]byte, error) {
	// Accumulate per (group, verbs) so one marker covers every resource in a
	// group, matching how the markers were written by hand.
	type key struct{ group, verbs string }
	acc := map[key]map[string]bool{}
	add := func(group, resource, verbs string) {
		k := key{group, verbs}
		if acc[k] == nil {
			acc[k] = map[string]bool{}
		}
		acc[k][resource] = true
	}

	for _, s := range specs {
		src := pluralize(s.Source.Kind)
		add(s.Source.Group, src, sourceVerbs)
		// Subresources carry their own verbs: status is updated by the mirror,
		// finalizers only ever need update.
		add(s.Source.Group, src+"/status", "get;update;patch")
		add(s.Source.Group, src+"/finalizers", "update")
		for _, e := range s.Emit {
			add(e.Target.Group, pluralize(e.Target.Kind), targetVerbs)
		}
	}

	rules := make([]rule, 0, len(acc))
	for k, set := range acc {
		res := make([]string, 0, len(set))
		for r := range set {
			res = append(res, r)
		}
		sort.Strings(res)
		rules = append(rules, rule{group: k.group, resources: res, verbs: k.verbs})
	}
	// Deterministic output: a generator whose output reorders on every run
	// produces noise diffs and defeats the -check mode.
	sort.Slice(rules, func(i, j int) bool {
		if rules[i].group != rules[j].group {
			return rules[i].group < rules[j].group
		}
		return strings.Join(rules[i].resources, ";") < strings.Join(rules[j].resources, ";")
	})

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by hack/gen-rbac from %s. DO NOT EDIT.
//
// Regenerate with: make generate-rbac
//
// These markers are what controller-gen turns into the manager ClusterRole.
// They are derived from the FieldMapping documents, so onboarding a vendor
// needs no Go edit: drop in a mapping and regenerate. The previous hand-written
// markers were the one place a vendor port was not pure data, and a forgotten
// group surfaced only at runtime as an apiserver Forbidden error.

package %s

`, mappingDir, pkg)

	for _, r := range rules {
		fmt.Fprintf(&b, "// +kubebuilder:rbac:groups=%s,resources=%s,verbs=%s\n",
			r.group, strings.Join(r.resources, ";"), r.verbs)
	}
	return b.Bytes(), nil
}

// pluralize lowercases a Kind and pluralizes it the way the Kubernetes API
// does, which is what controller-gen expects in a resources= list.
//
// DataProcessingUnit -> dataprocessingunits, DSCNodePolicy -> dscnodepolicies,
// BFB -> bfbs, DPUService -> dpuservices.
func pluralize(kind string) string {
	s := strings.ToLower(kind)
	switch {
	case s == "":
		return s
	case strings.HasSuffix(s, "s"), strings.HasSuffix(s, "x"), strings.HasSuffix(s, "z"),
		strings.HasSuffix(s, "ch"), strings.HasSuffix(s, "sh"):
		return s + "es"
	case strings.HasSuffix(s, "y") && len(s) > 1 && !isVowel(s[len(s)-2]):
		return s[:len(s)-1] + "ies"
	default:
		return s + "s"
	}
}

func isVowel(b byte) bool {
	return strings.IndexByte("aeiou", b) >= 0
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-rbac: "+format+"\n", args...)
	os.Exit(1)
}
